### ISSUE TITLE
Detect a click in a WebView ?

### ISSUE THREAD

**Issue by Javdu10** [AvengeMedia/natrium_wallet_flutter#1]
Hi, how hard would it be to detect a click of a button, let’s say the BrainBlocks one within a Web page and automatically create a send transaction in the wallet ? 
This way we could have something like Wechat Pay within the wallet it would be a really good feature
PS : i really love the design of the wallet !

**Comment by bbedward** [comment]
Thanks,

Natrium already supports deep links if that's what you're referring to. If you checkout nanocrawler.cc and tap any QR code from mobile, you'll see what I mean.

**Comment by Javdu10** [comment]
Oh nice, I’ll open the issue on the BrainBlocks button then, how come they don’t have a deep link on it ? 😩

**Comment by bbedward** [comment]
Not sure, but it also supports an amount - so it will prefill the amount also if it's in the link
